Enable route_settings in default stage
terraform-aws-modules/terraform-aws-apigateway-v2 pull request #80
Opened 2022-09-09 10:30 UTC by honglus

## Description
Enable route_settings in default stage
route_settings will override default_settings, So even I just want to set throttling_rate_limit on route "POST /test", I have to set the remaining variables to use default_route_settings values, otherwise it will be AWS default value not default_route_settings value. e.g detailed_metrics_enabled will become false.
- Enable route_settings and add only the route with at least one of the options:
data_trace_enabled, logging_level, throttling_burst_limit, throttling_rate_limit, detailed_metrics_enabled is not null
- set the remaining variables to use use default_route_settings values

## Motivation and Context
#78 

## Breaking Changes
No

## How Has This Been Tested?
I have tested and deployed to my company AWS environment.

2022-09-09 14:44 UTC, antonbabenko requested changes
Please verify and update `examples/complete-http` to work with proposed changes. Now I run it and got these errors:
```
╷
│ Error: error creating API Gateway v2 stage: NotFoundException: Unable to find Route by key GET /some-route within the provided RouteSettings
│ {
│   RespMetadata: {
│     StatusCode: 404,
│     RequestID: "0bedb742-75a3-43b4-975a-c0b0a986fd48"
│   },
│   Message_: "Unable to find Route by key GET /some-route within the provided RouteSettings"
│ }
│ 
│   with module.api_gateway.aws_apigatewayv2_stage.default[0],
│   on ../../main.tf line 63, in resource "aws_apigatewayv2_stage" "default":
│   63: resource "aws_apigatewayv2_stage" "default" {
│ 
╵
╷
│ Error: error creating API Gateway v2 route: BadRequestException: Invalid Route authorization type specified. Authorization Scopes are only valid for COGNITO_USER_POOLS and JWT authorization types
│ 
│   with module.api_gateway.aws_apigatewayv2_route.this["GET /some-route-with-authorizer-and-different-scope"],
│   on ../../main.tf line 121, in resource "aws_apigatewayv2_route" "this":
│  121: resource "aws_apigatewayv2_route" "this" {
│ 
╵
╷
│ Error: error creating API Gateway v2 route: BadRequestException: Invalid Route authorization type specified. Authorization Scopes are only valid for COGNITO_USER_POOLS and JWT authorization types
│ 
│   with module.api_gateway.aws_apigatewayv2_route.this["GET /some-route-with-authorizer-and-scope"],
│   on ../../main.tf line 121, in resource "aws_apigatewayv2_route" "this":
│  121: resource "aws_apigatewayv2_route" "this" {
│ 
╵
```

2022-09-11 05:20 UTC, honglus commented
sorry, it is not easy for me to provision all resources in the example. Can you try
1) examples/complete-http is successful before the change.
2) try to pin AWS version to v4.25.0, which is the version I tested successfully for my company's resource.

2022-09-12 10:07 UTC, antonbabenko commented
I am pretty sure that example worked before this PR. I will take a look into this PR during this week.

2022-09-12 13:10 UTC, antonbabenko approved these changes

2022-09-12 13:11 UTC, merged

2022-09-12 13:11 UTC, antonbabenko commented
This PR is included in version 2.2.0 :tada: